apiVersion: v1
kind: Namespace
metadata:
  name: ks-load
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: ks-load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: http-server
        image: corest/build:kubeshark-load-test-nginx-0.0.2
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ks-load
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-load-test
  namespace: ks-load
spec:
  replicas: 3  # Number of replicas
  selector:
    matchLabels:
      app: k6-load-test
  template:
    metadata:
      labels:
        app: k6-load-test
    spec:
      containers:
      - name: k6
        image: corest/build:kubeshark-load-test-grafana-k6-0.0.3
        env:
          - name: VUS
            value: "100"
          - name: DURATION
            value: "3h"
          - name: URL
            value: "http://server.ks-load.svc.cluster.local/smap.png"
          - name: SLEEP
            value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: k6-load-test
  namespace: ks-load
spec:
  selector:
    app: k6-load-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80