apiVersion: v1
kind: Namespace
metadata:
  name: ks-load-mert-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http1-server
  namespace: ks-load-mert-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http1-server
  template:
    metadata:
      labels:
        app: http1-server
    spec:
      containers:
      - name: http1-server
        image: kubeshark/k6s-load-server:v52.3.88
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: http1-server
  namespace: ks-load-mert-2
spec:
  selector:
    app: http1-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http1-client
  namespace: ks-load-mert-2
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: http1-client
  template:
    metadata:
      labels:
        app: http1-client
    spec:
      containers:
      - name: k6
        image: kubeshark/k6s-load-test:v52.3.88
        imagePullPolicy: Always
        env:
          - name: VUS
            value: "1"
          - name: DURATION
            value: "12h"
          - name: URL
            value: "http://http1-server.ks-load-mert-2.svc.cluster.local/smap.png" # "https://nghttp2.org" 
          - name: SLEEP
            value: "10"
          # - name: CONNECTION
          #   value: "keep-alive"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2-client
  namespace: ks-load-mert-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http2-client
  template:
    metadata:
      labels:
        app: http2-client
    spec:
      containers:
      - name: http2-client
        image: kubeshark/go-http2-client:v52.3.88
        imagePullPolicy: Always
        env:
          - name: URL
            value: "http://http2-server.ks-load-mert-2.svc.cluster.local/"  # The URL to send requests to
          - name: "N"
            value: "10"  # Number of requests to send per connection
          - name: "D"
            value: "2"  # Delay between requests in seconds
          - name: "V"
            value: "2"  # HTTP version (1 or 2)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http2-server
  namespace: ks-load-mert-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http2-server
  template:
    metadata:
      labels:
        app: http2-server
    spec:
      containers:
      - name: http2-server
        image: kubeshark/go-http2-server:v52.3.88
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http2-server
  namespace: ks-load-mert-2
spec:
  selector:
    app: http2-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
