# Use the official httpd image as the base image
FROM httpd:latest

# Copy the HTML files into the default directory served by httpd
COPY files/smap.png /usr/local/apache2/htdocs/
COPY files/ks_logo.png /usr/local/apache2/htdocs/
